name: Test Worklow
on: [workflow_dispatch]
jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - id: 'auth'
            uses: 'google-github-actions/auth@v3'
            with:
              credentials_json: '${{ secrets.GCP_SA_KEY }}'
          - name: 'Use gcloud CLI'
            run: 'gcloud auth list'
