name: Test Worklow
on: [workflow_dispatch]
jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - id: 'auth'
            uses: 'google-github-actions/auth@v3'
            with:
              
              service_account: kubernetes-cluster-admin@fabled-era-467617-p0.iam.gserviceaccount.com
          - name: 'Use gcloud CLI'
            run: 'gcloud auth list'
