name: Test Worklow
on: [workflow_dispatch]
jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - id: 'auth'
            uses: 'google-github-actions/auth@v3'

            env:
              GCP_SA_KEY: ${{ secrets.GOOGLE_CREDENTIALS }}
            with:
              credentials_json: ${{ env.GCP_SA_KEY }}
   
          - name: 'Use gcloud CLI'
          
            run: |
              gcloud auth list
              echo "${{ secrets.GOOGLE_CREDENTIALS }}" > /tmp/key.json
              gcloud auth activate-service-account --key-file=/tmp/key.json
              gcloud config set project YOUR_GCP_PROJECT_ID 
              gcloud auth list
