name: Connection with VPC on loveleenmatta2 account
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  vpc-connection:
    runs-on: ubuntu-latest

    steps:
     - name: checkout code
       uses: actions/checkout@v3

     - name: Authenticate to Gcloud
       uses: google-github-actions/auth@v3
       with:
         #credentials_json: '${{ secrets.GCP_SA_KEY }}'
         workload_identity_provider: 'projects/145229495924/locations/global/workloadIdentityPools/github-actions/providers/github-provider'

     - name: gcloud auth list
       run:  'gcloud auth list'
  
     - name: Configure SDK Cloud
       uses: google-github-actions/setup-gcloud@v2

    #  - name: Create VPC connection on loveleenmatta2 account
    #    run:  |
    #     gcloud compute networks peerings create lm-vpc-connection \
    #     --network=lm-vpc \
    #     --peer-project=fabled-era-467617-p0 \
    #     --peer-network=default \
    #     --auto-create-routes \
    #     --project=project-22b32090-5bb2-4730-a69  
    #    env:
    #     GCP_PROJECT_ID: project-22b32090-5bb2-4730-a69
